import { SCROLL_CHROME_PINNED_TOOLBAR_HEIGHT } from './scrollChrome';

export {
  SCROLL_CHROME_COLLAPSED_TITLE_FADE_IN_END as CHATS_COLLAPSED_TITLE_FADE_IN_END,
  SCROLL_CHROME_COLLAPSED_TITLE_FADE_IN_START as CHATS_COLLAPSED_TITLE_FADE_IN_START,
  SCROLL_CHROME_COLLAPSED_TITLE_FONT_SIZE as CHATS_COLLAPSED_TITLE_FONT_SIZE,
  SCROLL_CHROME_FADE_OUT_END as CHATS_CHROME_FADE_OUT_END,
  SCROLL_CHROME_SLIDE_END as CHATS_CHROME_SLIDE_END,
} from './scrollChrome';

export { HOME_SCROLL_BOTTOM_LOCK_THRESHOLD as CHATS_SCROLL_BOTTOM_LOCK_THRESHOLD } from './homeChrome';

/** Pinned toolbar height when the header is collapsed (back button row). */
export const CHATS_COLLAPSED_HEADER_HEIGHT = SCROLL_CHROME_PINNED_TOOLBAR_HEIGHT;
